name: Build Test .exe
on:
  push:
    tags:
      - 'Issue_*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install pyinstaller
      - name: Build EXE
        run: pyinstaller --onefile change_java_version.py
      - name: Test Executable
        run: .\dist\change_java_version.exe -h